# Decide to install AlmaLinux RDP method

- name: Include AlmaLinux xrdp setup
  ansible.builtin.include_tasks: AlmaLinux-xrdp.yml
  when: ansible_distribution == "AlmaLinux" and (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")

- name: Install gnome-remote-desktop for AlmaLinux 10
  ansible.builtin.include_tasks: gnome-remote-desktop.yml
  when: ansible_distribution == "AlmaLinux" and ansible_distribution_major_version == "10"

# Shared Tasks between AlmaLinux RDP methods

- name: allow traffic over 3389
  ansible.posix.firewalld:
    port: 3389/tcp
    permanent: true
    state: enabled
  become: true

- name: reboot
  ansible.builtin.reboot:
  become: true
