---
- name: Install EPEL
  become: true
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install GNOME desktop group
  become: true
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present

- name: Set default to graphical.target
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/default.target
    state: link
    src: /usr/lib/systemd/system/graphical.target

- name: Install xrdp, xorg backend and X11 helpers
  become: true
  ansible.builtin.package:
    name:
      - xrdp
      - xorgxrdp
      - xorg-x11-xauth
      - xorg-x11-xinit
    state: present

- name: Write /etc/xrdp/startwm.sh
  become: true
  ansible.builtin.copy:
    dest: /etc/xrdp/startwm.sh
    mode: '0755'
    content: |
      #!/bin/sh
      [ -r /etc/profile ] && . /etc/profile
      if [ -r /etc/X11/xinit/Xsession ]; then exec /etc/X11/xinit/Xsession; fi
      if [ -r /etc/X11/Xsession ]; then exec /etc/X11/Xsession; fi
      if command -v gnome-session >/dev/null 2>&1; then
        export GNOME_SHELL_SESSION_MODE=classic
        export XDG_SESSION_DESKTOP=GNOME
        export XDG_CURRENT_DESKTOP=GNOME
        exec gnome-session
      fi
      exec /usr/bin/xterm

- name: Remove earlier managed Xorg session block
  become: true
  ansible.builtin.blockinfile:
    path: /etc/xrdp/xrdp.ini
    marker: "; {mark} MANAGED XORG SESSION"
    state: absent

- name: Install Xorg server
  become: true
  ansible.builtin.package:
    name: xorg-x11-server-Xorg
    state: present
  register: xorg_srv

- name: Check if Xorg is already present
  become: true
  ansible.builtin.command: grep -q '^\[Xorg\]' /etc/xrdp/xrdp.ini
  register: has_xorg
  changed_when: false
  failed_when: has_xorg.rc not in [0, 1]

- name: Ensure Xorg session exists
  become: true
  ansible.builtin.blockinfile:
    path: /etc/xrdp/xrdp.ini
    marker: "; {mark} MANAGED XORG SESSION"
    insertafter: EOF
    block: |
      [Xorg]
      name=Xorg
      lib=libxorgxrdp.so
      username=ask
      password=ask
      ip=127.0.0.1
      port=-1
      code=20
  register: xrdp_ini_xorg
  when: has_xorg.rc == 1

- name: Check if Xorg is already present in sesman.ini
  become: true
  ansible.builtin.command: grep -q '^\[Xorg\]' /etc/xrdp/sesman.ini
  register: has_sesman_xorg
  changed_when: false
  failed_when: has_sesman_xorg.rc not in [0, 1]

- name: Ensure Xorg block in sesman.ini
  become: true
  ansible.builtin.blockinfile:
    path: /etc/xrdp/sesman.ini
    marker: "; {mark} MANAGED XORG SESMAN"
    insertafter: EOF
    block: |
      [Xorg]
      param=/usr/libexec/Xorg
      param=-noreset
      param=-nolisten
      param=tcp
      param=-logfile
      param=.xorgxrdp.%s.log
  register: sesman_xorg_block
  when: has_sesman_xorg.rc == 1

- name: Ensure sesman uses /usr/libexec/Xorg
  become: true
  ansible.builtin.lineinfile:
    path: /etc/xrdp/sesman.ini
    regexp: '^param=Xorg$|^param=.*/Xorg$'
    line: 'param=/usr/libexec/Xorg'
    insertafter: '^\[Xorg\]'
    backup: true
  register: sesman_xorg_path
  failed_when: false

- name: Ensure xrdp lib dirs exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /usr/lib64/xrdp
    - /usr/lib/xrdp

- name: Copy libxorgxrdp.so to /usr/lib64/xrdp
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /usr/lib64/xorg/modules/libxorgxrdp.so
    dest: /usr/lib64/xrdp/libxorgxrdp.so
    mode: '0644'
    force: true
  register: copy_xorg_64_force
  failed_when: false

- name: If 64-bit source is not present copy to /usr/lib/xrdp instead
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /usr/lib/xorg/modules/libxorgxrdp.so
    dest: /usr/lib/xrdp/libxorgxrdp.so
    mode: '0644'
    force: true
  register: copy_xorg_32_force
  failed_when: false

- name: Restore SELinux context on xrdp libs
  become: true
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  failed_when: false
  loop:
    - restorecon -v /usr/lib64/xrdp/libxorgxrdp.so
    - restorecon -v /usr/lib/xrdp/libxorgxrdp.so

- name: Choose absolute lib path we actually have
  become: true
  ansible.builtin.stat:
    path: /usr/lib64/xrdp/libxorgxrdp.so
  register: have_lib64

- name: Set fact for absolute xorg lib path
  ansible.builtin.set_fact:
    xorg_lib_path: "{{ '/usr/lib64/xrdp/libxorgxrdp.so' if have_lib64.stat.exists else '/usr/lib/xrdp/libxorgxrdp.so' }}"

- name: Point Xorg lib to absolute path in xrdp.ini
  become: true
  ansible.builtin.lineinfile:
    path: /etc/xrdp/xrdp.ini
    regexp: '^lib='
    line: "lib={{ xorg_lib_path }}"
    insertafter: '^\[Xorg\]'
    backup: true
  register: xrdp_ini_lib_abs

- name: Disable Xvnc session in xrdp.ini
  become: true
  ansible.builtin.replace:
    path: /etc/xrdp/xrdp.ini
    regexp: '(?ms)^\[Xvnc\]\n.*?(?=^\[|$\Z)'
    replace: '; [Xvnc] disabled by Ansible\n'
    backup: true
  register: xrdp_disable_xvnc

- name: Verify libxorgxrdp.so is accessible to xrdp
  become: true
  ansible.builtin.shell: |
    test -r /usr/lib64/xrdp/libxorgxrdp.so || test -r /usr/lib/xrdp/libxorgxrdp.so
  changed_when: false

- name: Enable and start xrdp
  become: true
  ansible.builtin.service:
    name: xrdp
    state: started
    enabled: true

- name: Restart xrdp if Xorg config changed
  become: true
  ansible.builtin.service:
    name: xrdp
    state: restarted
  when: >
    xorg_srv.changed or
    xrdp_ini_xorg.changed or
    sesman_xorg_path.changed or
    sesman_xorg_block.changed | default(false) or
    copy_xorg_64_force.changed | default(false) or
    copy_xorg_32_force.changed | default(false) or
    xrdp_ini_lib_abs.changed | default(false) or
    xrdp_disable_xvnc.changed | default(false)

- name: Install firewalld
  become: true
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Allow RDP in firewalld when running
  become: true
  ansible.posix.firewalld:
    service: rdp
    state: enabled
    permanent: true
    immediate: true
  when:
    - "'firewalld.service' in ansible_facts.services"
    - ansible_facts.services['firewalld.service'].state == 'running'

- name: Install SELinux utils/policy
  become: true
  ansible.builtin.package:
    name:
      - policycoreutils-python-utils
      - xrdp-selinux
    state: present
