---
- name: Install EPEL
  become: true
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install GNOME desktop group
  become: true
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present

- name: Set default.target to graphical.target
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/default.target
    state: link
    src: /usr/lib/systemd/system/graphical.target

- name: Install XRDP and Xorg
  become: true
  ansible.builtin.package:
    name:
      - xrdp
      - xorgxrdp
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-xinit
      - dbus-x11
      - gnome-session
      - gnome-shell
      - gnome-classic-session
      - xterm
    state: present

- name: Write /etc/xrdp/startwm.sh
  become: true
  ansible.builtin.copy:
    dest: /etc/xrdp/startwm.sh
    mode: '0755'
    content: |
      #!/bin/sh
      [ -r /etc/profile ] && . /etc/profile

      export XDG_SESSION_TYPE=x11
      export GNOME_SHELL_SESSION_MODE=classic
      export XDG_SESSION_DESKTOP=GNOME
      export XDG_CURRENT_DESKTOP=GNOME

      if command -v dbus-launch >/dev/null 2>&1; then
        exec dbus-launch --exit-with-session gnome-session --session=gnome-classic --disable-acceleration-check
      fi

      if command -v gnome-session >/dev/null 2>&1; then
        exec gnome-session --session=gnome-classic --disable-acceleration-check
      fi

      [ -r /etc/X11/xinit/Xsession ] && exec /etc/X11/xinit/Xsession
      [ -r /etc/X11/Xsession ] && exec /etc/X11/Xsession
      exec /usr/bin/xterm

- name: Ensure Xorg in /etc/xrdp/sesman.ini
  become: true
  ansible.builtin.blockinfile:
    path: /etc/xrdp/sesman.ini
    marker: "; {mark} MANAGED XORG SESMAN"
    insertafter: EOF
    block: |
      [Xorg]
      param=/usr/libexec/Xorg
      param=-noreset
      param=-nolisten
      param=tcp
      param=-logfile
      param=.xorgxrdp.%s.log
  register: sesman_xorg

- name: Point sesman to startwm.sh as the default
  become: true
  ansible.builtin.ini_file:
    path: /etc/xrdp/sesman.ini
    section: Globals
    option: DefaultWindowManager
    value: /etc/xrdp/startwm.sh
    backup: true
  register: sesman_default

- name: Ensure Xorg in xrdp.ini
  become: true
  ansible.builtin.blockinfile:
    path: /etc/xrdp/xrdp.ini
    marker: "; {mark} MANAGED XORG SESSION"
    insertafter: EOF
    block: |
      [Xorg]
      name=Xorg
      username=ask
      password=ask
  register: xrdp_ini_xorg

- name: Set Xorg session lib=libxup.so
  become: true
  ansible.builtin.ini_file:
    path: /etc/xrdp/xrdp.ini
    section: Xorg
    option: lib
    value: libxup.so
  register: ini_lib

- name: Ensure Xorg session
  become: true
  ansible.builtin.ini_file:
    path: /etc/xrdp/xrdp.ini
    section: Xorg
    option: code
    value: "20"
  register: ini_code

- name: Remove ip from Xorg
  become: true
  ansible.builtin.ini_file:
    path: /etc/xrdp/xrdp.ini
    section: Xorg
    option: ip
    state: absent
  register: remove_ip_ini

- name: Disable Xvnc
  become: true
  ansible.builtin.replace:
    path: /etc/xrdp/xrdp.ini
    regexp: '(?ms)^\[Xvnc\]\n.*?(?=^\[|$\Z)'
    replace: '; [Xvnc] disabled by Ansible\n'
    backup: true
  register: xrdp_disable_xvnc

- name: Enable and start xrdp
  become: true
  ansible.builtin.service:
    name: xrdp
    state: started
    enabled: true

- name: Restart xrdp if config changed
  become: true
  ansible.builtin.service:
    name: xrdp
    state: restarted
  when: >
    sesman_xorg.changed or
    xrdp_ini_xorg.changed or
    ini_lib.changed or
    ini_code.changed or
    remove_ip_ini.changed or
    xrdp_disable_xvnc.changed or
    sesman_default.changed

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Allow 3389/tcp in firewalld when running
  become: true
  ansible.posix.firewalld:
    service: rdp
    state: enabled
    permanent: true
    immediate: true
  when:
    - "'firewalld.service' in ansible_facts.services"
    - ansible_facts.services['firewalld.service'].state == 'running'

- name: Wait for xrdp to listen on 3389
  ansible.builtin.wait_for:
    port: 3389
    timeout: 30
    state: started

- name: Install SELinux utils/policy
  become: true
  ansible.builtin.package:
    name:
      - policycoreutils-python-utils
      - xrdp-selinux
    state: present
