---
- name: install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present
  become: true

- name: Install xrpd
  ansible.builtin.package:
    name: xrdp
    state: present
  become: true

- name: Enable XRDP service
  ansible.builtin.systemd_service: 
    name: xrdp
    state: started
    enabled: true
  become: true