---
- name: Install winpr-utils for generating certificate
  ansible.builtin.package:
    name: winpr-utils
    state: present

- name: Generate certificate
  ansible.builtin.command: winpr-makecert -silent -rdp -path ~gnome-remote-desktop rdp-tls
  become: true
  become_user: gnome-remote-desktop

- name: Add TLS cert
  ansible.builtin.command: grdctl --system rdp set-tls-key ~gnome-remote-desktop/rdp-tls.key
  become: true

- name: Add TLS key
  ansible.builtin.command: grdctl --system rdp set-tls-cert ~gnome-remote-desktop/rdp-tls.crt
  become: true

- name: Setup RDP credentials
  ansible.builtin.command: grdctl --system rdp set-credentials "{{ RDP_USER }}" "{{ RDP_PASSWORD }}"
  become: true

- name: Enable RDP
  ansible.builtin.command: grdctl --system rdp enable
  become: true

- name: Enable RDP service
  ansible.builtin.command: systemctl --now enable gnome-remote-desktop.service
  become: true

- name: Reboot
  ansible.builtin.reboot:
