# Decide to install Ubuntu RDP method

- name: Include Ubuntu xrdp setup
  ansible.builtin.include_tasks: Ubuntu-xrdp.yml
  when: ansible_distribution == "Ubuntu" and (ansible_distribution_major_version == "20" or ansible_distribution_major_version == "22")

- name: Install gnome-remote-desktop for Ubuntu 24
  ansible.builtin.include_tasks: gnome-remote-desktop.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "24"

# Shared Tasks between Ubuntu RDP methods

- name: reboot
  ansible.builtin.reboot:
  become: true
